/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProject: typeof import('./src/components/AddProject.vue')['default']
    EditTasks: typeof import('./src/components/EditTasks.vue')['default']
    ProjectBoard: typeof import('./src/components/ProjectBoard.vue')['default']
    RenameProject: typeof import('./src/components/RenameProject.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TasksDisplayFinishedTask: typeof import('./src/components/TasksDisplayFinishedTask.vue')['default']
    TasksDisplayUnfinishedTask: typeof import('./src/components/TasksDisplayUnfinishedTask.vue')['default']
    TaskStatusDropdown: typeof import('./src/components/TaskStatusDropdown.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  }
}
